export const db = [
  {
    // date: new Date().toISOString().split("T")[0],
    date: "2023-04-19",
    status: "liked",
    dayEvents: ["fdsgsg", "fjhjdshgh", "sdlfjgsjdf"],
    userId: "12345",
    userName: "test",
    userEmail: "test@test.com",
  },
  {
    date: "2023-04-18",
    status: "did",
    dayEvents: ["fdsgsg", "fjhjdshgh", "sdlfjgsjdf", "ldyfjgfgu"],
    userId: "12345",
    userName: "test",
    userEmail: "test@test.com",
  },
  {
    date: "2023-04-17",
    status: "did",
    dayEvents: ["fdsgsg", "fjhjdshgh", "sdlfjgsjdf", "ldyfjgfgu"],
    userId: "12345",
    userName: "test",
    userEmail: "test@test.com",
  },
  {
    date: "2023-04-16",
    status: "did",
    dayEvents: ["fdsgsg", "fjhjdshgh", "sdlfjgsjdf", "ldyfjgfgu"],
    userId: "12345",
    userName: "test",
    userEmail: "test@test.com",
  },
  {
    date: "2023-04-15",
    status: "did",
    dayEvents: ["fdsgsg", "fjhjdshgh", "sdlfjgsjdf", "ldyfjgfgu"],
    userId: "12345",
    userName: "test",
    userEmail: "test@test.com",
  },
];
